# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/forms_ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 581)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gview = QtWidgets.QGraphicsView(self.centralwidget)
        self.gview.setObjectName("gview")
        self.gridLayout_2.addWidget(self.gview, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.moveUpButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveUpButton.setObjectName("moveUpButton")
        self.gridLayout.addWidget(self.moveUpButton, 1, 1, 1, 1)
        self.moveLeftDownButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveLeftDownButton.setObjectName("moveLeftDownButton")
        self.gridLayout.addWidget(self.moveLeftDownButton, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.moveRightUpButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveRightUpButton.setObjectName("moveRightUpButton")
        self.gridLayout.addWidget(self.moveRightUpButton, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        self.moveDownButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveDownButton.setObjectName("moveDownButton")
        self.gridLayout.addWidget(self.moveDownButton, 3, 1, 1, 1)
        self.moveLeftUpButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveLeftUpButton.setObjectName("moveLeftUpButton")
        self.gridLayout.addWidget(self.moveLeftUpButton, 1, 0, 1, 1)
        self.moveLeftButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveLeftButton.setObjectName("moveLeftButton")
        self.gridLayout.addWidget(self.moveLeftButton, 2, 0, 1, 1)
        self.moveRightButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveRightButton.setObjectName("moveRightButton")
        self.gridLayout.addWidget(self.moveRightButton, 2, 2, 1, 1)
        self.moveRightDownButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveRightDownButton.setObjectName("moveRightDownButton")
        self.gridLayout.addWidget(self.moveRightDownButton, 3, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Safonov CG2"))
        self.moveUpButton.setText(_translate("MainWindow", "^"))
        self.moveLeftDownButton.setText(_translate("MainWindow", "/"))
        self.moveRightUpButton.setText(_translate("MainWindow", "/"))
        self.moveDownButton.setText(_translate("MainWindow", "\\/"))
        self.moveLeftUpButton.setText(_translate("MainWindow", "\\"))
        self.moveLeftButton.setText(_translate("MainWindow", "<-"))
        self.moveRightButton.setText(_translate("MainWindow", "->"))
        self.moveRightDownButton.setText(_translate("MainWindow", "\\"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
